LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := SDIOS-Client
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := SDIOS-Client-release.apk
LOCAL_MODULE_CLASS := APPS
include $(BUILD_PREBUILT)
